#ifndef DEFINITIONS_H
# define DEFINITIONS_H

# define LEFT_JUSTIFY "-"
# define FORCE_SIGN "+"
# define BLANK_SPACE " "
# define SPECIFICATIONS "#"
# define PAD_ZERO "0"

// MIND CONFLICT WITH 0-9

# define PARAMETERS LEFT_JUSTIFY FORCE_SIGN BLANK_SPACE SPECIFICATIONS PAD_ZERO

#endif
